### PR TITLE
Minor font changes

### PR DESCRIPTION
**Pull request by ngyikp**
- Previously, Open Sans was applied only to select elements, but this
  would be tedious to do for every element, so it has been applied to
  the body tag.

  Plus, some elements was using "sans-serif" with quotes, which meant
  that the font change never happened as the browser was literally
  looking for a font named "sans-serif". This has been fixed.

- Add fallback to sans-serif in case Open Sans can't be loaded.

- Add a font-size to the body tag to ensure uniformity on different
  browsers.

- Give the store description some breathing space.

### CODE REVIEW

**Comment by blackhole12** [comment]
I was actually deliberately using "sans-serif" instead of Open Sans in many locations. Open Sans was usually used only in titles to make them look pretty. I'll take a look at this change later and see how it looks.

**Comment by ngyikp** [comment]
Actually, using "sans-serif" becomes serif or Times New Roman, that's probably not the effect you are intending :P

**Comment by blackhole12** [comment]
That is most definitely not what I intended, I just wanted something other than "Open Sans", really. I'll try to merge most of these changes in but I might change a few things back to proper sans-serif.

**Comment by ngyikp** [comment]
sans-serif is more commonly used as a fallback font if the alternate fonts
can't be loaded, what looks perfect on a Windows machine might look a bit
odd on Mac/Linux. I still suggest Open Sans for cross-OS consistency
though.

As long it's not Celestia Redux plastered all over the app, I'm fine with
whatever your choice may be :P

**Comment by blackhole12** [comment]
Cross-platform is a good point. I wonder if there's some other webfont out there that could contrast Open Sans?

**Pull request merged**
